# This file was generated by GitHub actions. DO NOT EDIT.
class AKashProviderServicesUnstable < Formula
  desc "Blockchain-powered decentralized compute platform"
  homepage "https://akash.network"
  version "0.1.0-rc13"

  on_macos do
    url "https://github.com/ovrclk/akash/releases/download/v0.1.0-rc13/provider-services_darwin_all.zip"
    sha256 "302e1a40f635cff1c587d92e578ed9cddd63fae6661d1b0700cb1826b94d88f6"

    def install
      bin.install "provider-services"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ovrclk/akash/releases/download/v0.1.0-rc13/akash_linux_arm64.zip"
      sha256 "b34131c6364b43f7f9fdbd0ac21d7c4ee4c3e910e6830d52d6e0625be84b9318"

      def install
        bin.install "provider-services"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ovrclk/akash/releases/download/v0.1.0-rc13/akash_linux_amd64.zip"
      sha256 "7c992cfe209e4673aff25369559450f4d87768f17b350361a24f5b40e5b5f3e2"

      def install
        bin.install "provider-services"
      end
    end
  end
  
  keg_only :unneeded, "This is unstable release"
  
end
