# This file was generated by GoReleaser. DO NOT EDIT.
class Akash < Formula
  desc "Blockchain-powered decentralized compute platform"
  homepage "https://akash.network"
  version "0.8.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/ovrclk/akash/releases/download/v0.8.1/akash_0.8.1_darwin_amd64.zip"
    sha256 "adc05f79b15a62baf94078a5cf916db67457dbd7a72b81c9513944e7a69f7fea"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/ovrclk/akash/releases/download/v0.8.1/akash_0.8.1_linux_amd64.zip"
      sha256 "7ef00d17478c165ed31c7f96191d1c7a90ab927738afca88e981adb1f5e95a33"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ovrclk/akash/releases/download/v0.8.1/akash_0.8.1_linux_arm64.zip"
        sha256 "645483b6ea3aa5aedcb22b4fb522b89c1724b12bcd84c740ad64689838909ccc"
      else
      end
    end
  end

  def install
    bin.install "akashctl"
    bin.install "akashd"
  end
end
