# This file was generated by GitHub actions. DO NOT EDIT.
class AkashProviderServicesUnstable < Formula
  desc "Blockchain-powered decentralized compute platform"
  homepage "https://akash.network"
  version "0.1.1-rc0"

  on_macos do
    url "https://github.com/ovrclk/provider-services/releases/download/v0.1.1-rc0/provider-services_darwin_all.zip"
    sha256 "2fdd3cd74d230f88f561a859dca420ca519e873561580c41fb996f7d31bee0d2"

    def install
      bin.install "provider-services"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ovrclk/provider-services/releases/download/v0.1.1-rc0/provider-services_linux_arm64.zip"
      sha256 "c249d2626792305bb3cf1257f811edd267448cdabb5f8518e21877466ef1776e"

      def install
        bin.install "provider-services"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ovrclk/provider-services/releases/download/v0.1.1-rc0/provider-services_linux_amd64.zip"
      sha256 "51a51e45cf4cb1c511a1ca8b8b76b9eb74b3e1b142d34b852901d4a5f8de3da3"

      def install
        bin.install "provider-services"
      end
    end
  end
  
  keg_only :unneeded, "This is unstable release"
  
end
