# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AkashEdge < Formula
  desc "Blockchain-powered decentralized compute platform"
  homepage "https://akash.network"
  version "0.17.2-rc6"

  on_macos do
    url "https://github.com/ovrclk/akash/releases/download/v0.17.2-rc6/akash_darwin_all.zip"
    sha256 "bde02ed74a42ab52d2b2393f5484a0d72fc46f1a32166587bf7ad2082d8b8fc6"

    def install
      bin.install "akash"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ovrclk/akash/releases/download/v0.17.2-rc6/akash_linux_arm64.zip"
      sha256 "ce65a0e304ce29be198c9c1a54c2d40721c2251ed8f9ed9f372b3a85a4a93efd"

      def install
        bin.install "akash"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ovrclk/akash/releases/download/v0.17.2-rc6/akash_linux_amd64.zip"
      sha256 "0837b3ce4a7565044453d9ec93a214d57fa4052a61478bb93fc357a574db9702"

      def install
        bin.install "akash"
      end
    end
  end

  keg_only :unneeded, "This is edgenet release. Run brew install ovrclk/tap/akash to install mainnet version"
end
