# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AkashEdge < Formula
  desc "Blockchain-powered decentralized compute platform"
  homepage "https://akash.network"
  version "0.14.1-rc4"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/ovrclk/akash/releases/download/v0.14.1-rc4/akash_0.14.1-rc4_darwin_amd64.zip"
    sha256 "8c4af396407fb72e8d9b4059b2be75719375fef39996ee89868cd3fe76645f4b"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/ovrclk/akash/releases/download/v0.14.1-rc4/akash_0.14.1-rc4_darwin_arm64.zip"
    sha256 "8337cb4c8d408fa1fe258130d03e44ad98b5f1f1253a9ec160c766a2d3429a63"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/ovrclk/akash/releases/download/v0.14.1-rc4/akash_0.14.1-rc4_linux_amd64.zip"
    sha256 "423e09f651728c80151bbd7623b8b7f72048d4b32db7d2dc7dcc2fc1d4104094"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/ovrclk/akash/releases/download/v0.14.1-rc4/akash_0.14.1-rc4_linux_arm64.zip"
    sha256 "b0bfd0b414d255db7dba5b5846e144045f1c848d0d6d3c21649362013aa59978"
  end

  keg_only :unneeded, "This is testnet release. Run brew install ovrclk/tap/akash to install mainnet version"

  def install
    bin.install "akash"
  end
end
