# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AkashTest < Formula
  desc "Blockchain-powered decentralized compute platform"
  homepage "https://akash.network"
  version "0.16.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/ovrclk/akash/releases/download/v0.16.0/akash_0.16.0_darwin_arm64.zip"
      sha256 "49a6a135165f6b2334c8fd5edd00af71d2a8b5ecb81fdce0c49a0036a89e83e1"

      def install
        bin.install "akash"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ovrclk/akash/releases/download/v0.16.0/akash_0.16.0_darwin_amd64.zip"
      sha256 "ddfef63000a7e3f3d816ff756ebea348f92d3d4112a818f490d5d36b60b1ce12"

      def install
        bin.install "akash"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ovrclk/akash/releases/download/v0.16.0/akash_0.16.0_linux_arm64.zip"
      sha256 "9c137f6fc33b4502908846599f31df40ed5093a6d2a9cc63e2c1a689085369e1"

      def install
        bin.install "akash"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ovrclk/akash/releases/download/v0.16.0/akash_0.16.0_linux_amd64.zip"
      sha256 "7ce59e5a2ef0869ac3d9f6cf53666ce488b20a037a91b4fb457b2d8bd4256ef0"

      def install
        bin.install "akash"
      end
    end
  end

  keg_only :unneeded, "This is testnet release. Run brew install ovrclk/tap/akash to install mainnet version"
end
