# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AkashTest < Formula
  desc "Blockchain-powered decentralized compute platform"
  homepage "https://akash.network"
  version "0.16.4-rc4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ovrclk/akash/releases/download/v0.16.4-rc4/akash_0.16.4-rc4_darwin_amd64.zip"
      sha256 "11f023831828038c6e78a31487462161b14efd90b691d867d5ef472dc8511a71"

      def install
        bin.install "akash"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ovrclk/akash/releases/download/v0.16.4-rc4/akash_0.16.4-rc4_darwin_arm64.zip"
      sha256 "582160489cad3706a4aea781af1decb694c45a91b06db8e16c1799853be012f5"

      def install
        bin.install "akash"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/ovrclk/akash/releases/download/v0.16.4-rc4/akash_0.16.4-rc4_linux_amd64.zip"
      sha256 "95b241883478f2486f90baf24000391204a8685020e0dc3ec8df4a02aaa87942"

      def install
        bin.install "akash"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ovrclk/akash/releases/download/v0.16.4-rc4/akash_0.16.4-rc4_linux_arm64.zip"
      sha256 "3f0fcf7b6de4c4afa524e60b41f8fb7917681a88186653c24fb92f2b3cc75b36"

      def install
        bin.install "akash"
      end
    end
  end

  keg_only :unneeded, "This is testnet release. Run brew install ovrclk/tap/akash to install mainnet version"
end
