# This file was generated by GitHub actions. DO NOT EDIT.
class AKashProviderServices < Formula
  desc "Blockchain-powered decentralized compute platform"
  homepage "https://akash.network"
  version "0.1.0-rc14"

  on_macos do
    url "https://github.com/ovrclk/akash/releases/download/v0.1.0-rc14/provider-services_darwin_all.zip"
    sha256 "25850a4c468b31295aa2d0976bc82a89b7037fcb9bfda7efee855a60acdb50ad"

    def install
      bin.install "provider-services"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ovrclk/akash/releases/download/v0.1.0-rc14/akash_linux_arm64.zip"
      sha256 "442a95d5855405a4e943203c3edf800b52dab1bb627e2d78ec0b7050a1466e47"

      def install
        bin.install "provider-services"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ovrclk/akash/releases/download/v0.1.0-rc14/akash_linux_amd64.zip"
      sha256 "d57265ff1f44a08f27e8d3ff28d294f14eb5ad96f1ba69a9c407c84c1f482059"

      def install
        bin.install "provider-services"
      end
    end
  end
  
end
