# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Akash < Formula
  desc "Blockchain-powered decentralized compute platform"
  homepage "https://akash.network"
  version "0.16.8"

  on_macos do
    url "https://github.com/ovrclk/akash/releases/download/v0.16.8/akash_0.16.8_darwin_all.zip"
    sha256 "4b487f4bea642aae56b5e7c7f6f417b343c92a024b1109a45cae1b40d3f46609"

    def install
      bin.install "akash"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/ovrclk/akash/releases/download/v0.16.8/akash_0.16.8_linux_amd64.zip"
      sha256 "1741b269210005dd82a9f0a4dbfd30e6290106bab34984bafef0209798c97014"

      def install
        bin.install "akash"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ovrclk/akash/releases/download/v0.16.8/akash_0.16.8_linux_arm64.zip"
      sha256 "cfc5b62f85c31706b647bddba099dcbc9dda5d09e5d79e0d5855cc870e9cd278"

      def install
        bin.install "akash"
      end
    end
  end
end
