# This file was generated by GitHub actions. DO NOT EDIT.
class AkashProviderServices < Formula
  desc "Blockchain-powered decentralized compute platform"
  homepage "https://akash.network"
  version "0.5.11"

  on_macos do
    url "https://github.com/akash-network/provider/releases/download/v0.5.11/provider-services_darwin_all.zip"
    sha256 "73b901aa49afe71415857c732d3fa67435b72df5aa557114cf6bd5ca76229c09"

    def install
      bin.install "provider-services"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/akash-network/provider/releases/download/v0.5.11/provider-services_linux_arm64.zip"
      sha256 "e585f5d0ce7263212b9faae8e06869ee8d9e4f694fd2706c54ca0cbde1ad4f34"

      def install
        bin.install "provider-services"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/akash-network/provider/releases/download/v0.5.11/provider-services_linux_amd64.zip"
      sha256 "4b40a91089aca9adffb0b91684fbf5eacac57053ca645717109623f913dacbce"

      def install
        bin.install "provider-services"
      end
    end
  end
end
