# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Akt < Formula
  desc "Unified CLI for the Akash Network"
  homepage "https://akash.network"
  version "0.1.2"
  license "Apache-2.0"

  on_macos do
    url "https://github.com/akash-network/akt/releases/download/v0.1.2/akt_0.1.2_darwin_all.zip"
    sha256 "549c082c0dcedd4e553ef7c9c46d7c44acae5fcbe73d9311e58528fd3c105f12"

    define_method(:install) do
      bin.install "akt"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/akash-network/akt/releases/download/v0.1.2/akt_0.1.2_linux_amd64.zip"
      sha256 "fbb8c50884a79f212c3990c8c056205f7e1f7c64d3fca5ed02911172a3be107f"
      define_method(:install) do
        bin.install "akt"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/akash-network/akt/releases/download/v0.1.2/akt_0.1.2_linux_arm64.zip"
      sha256 "845a00935243a19615d34a1f1785c05225721daf6bb72c104ce2162833ca09d7"
      define_method(:install) do
        bin.install "akt"
      end
    end
  end

  test do
    system "#{bin}/akt", "version"
  end
end
