# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Akt < Formula
  desc "Unified CLI for the Akash Network"
  homepage "https://akash.network"
  version "0.0.2"
  license "Apache-2.0"

  on_macos do
    url "https://github.com/akash-network/akt/releases/download/v0.0.2/akt_0.0.2_darwin_all.zip"
    sha256 "00d5c3f01646ac85a349e8276a4a6d6b3bd9fe28aadc1180fd9fdeead487ced3"

    define_method(:install) do
      bin.install "akt"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/akash-network/akt/releases/download/v0.0.2/akt_0.0.2_linux_amd64.zip"
      sha256 "8506f01260d16735f9856669ab7ffff0e7ddd3a542d8ff0d4eb70e9b9d482a7a"
      define_method(:install) do
        bin.install "akt"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/akash-network/akt/releases/download/v0.0.2/akt_0.0.2_linux_arm64.zip"
      sha256 "83e4032631beb2a843f4aa24832600eade17b7ccf310f4c5264f4c10d3e7fc46"
      define_method(:install) do
        bin.install "akt"
      end
    end
  end

  test do
    system "#{bin}/akt", "version"
  end
end
