# This file was generated by GoReleaser. DO NOT EDIT.
cask "akt" do
  version "0.0.1"

  on_macos do
    url "https://github.com/akash-network/akt/releases/download/v#{version}/akt_#{version}_darwin_all.zip"
    sha256 "cb671634de70f3042e4b614ad4d1b067e0cd5006f63edcfb376a1a295a018124"
  end

  on_linux do
    on_intel do
      url "https://github.com/akash-network/akt/releases/download/v#{version}/akt_#{version}_linux_amd64.zip"
      sha256 "4440b7d1f8462cb0076cbc196781bd863fca7b61895fbf334ac0c5f86f087216"
    end
    on_arm do
      url "https://github.com/akash-network/akt/releases/download/v#{version}/akt_#{version}_linux_arm64.zip"
      sha256 "7796be99f2a06b2e3a5eaa2fa97d02b1bf93f476a0924b6fd5dfbf1b0bd10dd9"
    end
  end

  name "akt"
  desc "Unified CLI for the Akash Network"
  homepage "https://akash.network"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "akt"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/akt"]
    end
  end

  # No zap stanza required

end
