# This file was generated by GoReleaser. DO NOT EDIT.
cask "akt" do
  version "0.0.1-a6"

  on_macos do
    url "https://github.com/akash-network/akt/releases/download/v#{version}/akt_#{version}_darwin_all.zip"
    sha256 "df0eac588f2dde2c2de044d04a395fafde5da9dace9c96a9bc7e3024464b4cad"
  end

  on_linux do
    on_intel do
      url "https://github.com/akash-network/akt/releases/download/v#{version}/akt_#{version}_linux_amd64.zip"
      sha256 "cb77c5dc95ad051899af274b1c696576bd03e5f170680a78982c80f18f80b767"
    end
    on_arm do
      url "https://github.com/akash-network/akt/releases/download/v#{version}/akt_#{version}_linux_arm64.zip"
      sha256 "82072733237d9b1f8041cd24d731e17c8830b17a77a3ce3c3005ba7a9ea243dc"
    end
  end

  name "akt"
  desc "Unified CLI for the Akash Network"
  homepage "https://akash.network"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "akt"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/akt"]
    end
  end

  # No zap stanza required

end
